### ISSUE TITLE
Apt failure after CLI build

### ISSUE THREAD

**Issue by VernMcC** [sans-dfir/sift#153]
I used the latest CLI tool (v1.5.0-beta.0) to install sift on a fresh Ubuntu 16.04.2 64bit build.  There is nothing done to the system except:
- sudo apt update 
- sudo apt upgrade
- sudo apt update
- sudo apt --yes install open-vm-tools-desktop

Prior to the execution of the cli tool (it was gpg verified)
The install completes and reports no errors. After a reboot, the apt update and apt upgrade commands are executed, and 8 packages are in need of upgrading but when an upgrade is attempted, it fails:

sansforensics@siftworkstation:~$ sudo apt update
[sudo] password for sansforensics: 
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]    
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]  
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Hit:5 http://ppa.launchpad.net/gift/stable/ubuntu xenial InRelease             
Hit:6 http://archive.ubuntu.com/ubuntu xenial InRelease                        
Hit:7 http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial InRelease 
Hit:8 https://apt.dockerproject.org/repo ubuntu-xenial InRelease               
Hit:9 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu xenial InRelease           
Get:10 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [557 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [541 kB]
Hit:12 http://ppa.launchpad.net/sift/stable/ubuntu xenial InRelease            
Get:13 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 DEP-11 Metadata [298 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu xenial-updates/main DEP-11 64x64 Icons [200 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [485 kB]
Get:16 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [470 kB]
Get:17 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 DEP-11 Metadata [163 kB]
Get:18 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe DEP-11 64x64 Icons [208 kB]
Get:19 http://us.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 DEP-11 Metadata [2,520 B]
Get:20 http://us.archive.ubuntu.com/ubuntu xenial-backports/main amd64 DEP-11 Metadata [3,328 B]
Get:21 http://us.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 DEP-11 Metadata [4,672 B]
Get:22 http://security.ubuntu.com/ubuntu xenial-security/main amd64 DEP-11 Metadata [54.6 kB]
Get:23 http://security.ubuntu.com/ubuntu xenial-security/main DEP-11 64x64 Icons [45.7 kB]
Get:24 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 DEP-11 Metadata [35.8 kB]
Get:25 http://security.ubuntu.com/ubuntu xenial-security/universe DEP-11 64x64 Icons [52.2 kB]
Fetched 3,428 kB in 1s (2,318 kB/s)                                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
sansforensics@siftworkstation:~$ sudo apt upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  python-cffi-backend python-chardet python-cryptography python-enum34 python-idna python-ipaddress python-ndg-httpsclient python-openssl python-pyasn1 python-urllib3
Use 'sudo apt autoremove' to remove them.
The following packages have been kept back:
  python-dfvfs python-plaso
The following packages will be upgraded:
  python-dateutil python-requests python-zmq python3-pyparsing python3-requests python3-xlsxwriter
6 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Need to get 1,463 kB of archives.
After this operation, 2,945 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ppa.launchpad.net/gift/stable/ubuntu xenial/main amd64 python-dateutil amd64 2.5.3-2ppa1~xenial [189 kB]
Get:2 http://ppa.launchpad.net/gift/stable/ubuntu xenial/main amd64 python-requests all 2.11.1-1ppa1~xenial [356 kB]
Get:3 http://ppa.launchpad.net/gift/stable/ubuntu xenial/main amd64 python-zmq amd64 16.0.0-1ppa1~xenial [396 kB]
Get:4 http://ppa.launchpad.net/gift/stable/ubuntu xenial/main amd64 python3-pyparsing all 2.1.5-1ppa1~xenial [69.7 kB]
Get:5 http://ppa.launchpad.net/gift/stable/ubuntu xenial/main amd64 python3-requests all 2.11.1-1ppa1~xenial [356 kB]
Get:6 http://ppa.launchpad.net/gift/stable/ubuntu xenial/main amd64 python3-xlsxwriter all 0.9.3-1ppa1~xenial [96.0 kB]
Fetched 1,463 kB in 2s (506 kB/s)             
(Reading database ... 268268 files and directories currently installed.)
Preparing to unpack .../python-dateutil_2.5.3-2ppa1~xenial_amd64.deb ...
Unpacking python-dateutil (2.5.3-2ppa1~xenial) over (2.4.2-1) ...
Preparing to unpack .../python-requests_2.11.1-1ppa1~xenial_all.deb ...
Unpacking python-requests (2.11.1-1ppa1~xenial) over (2.9.1-3) ...
Preparing to unpack .../python-zmq_16.0.0-1ppa1~xenial_amd64.deb ...
Unpacking python-zmq (16.0.0-1ppa1~xenial) over (15.2.0-0ubuntu4) ...
Preparing to unpack .../python3-pyparsing_2.1.5-1ppa1~xenial_all.deb ...
Unpacking python3-pyparsing (2.1.5-1ppa1~xenial) over (2.0.3+dfsg1-1ubuntu0.1) ...
Preparing to unpack .../python3-requests_2.11.1-1ppa1~xenial_all.deb ...
Unpacking python3-requests (2.11.1-1ppa1~xenial) over (2.9.1-3) ...
Preparing to unpack .../python3-xlsxwriter_0.9.3-1ppa1~xenial_all.deb ...
Unpacking python3-xlsxwriter (0.9.3-1ppa1~xenial) over (0.7.3-1) ...
dpkg: error processing archive /var/cache/apt/archives/python3-xlsxwriter_0.9.3-1ppa1~xenial_all.deb (--unpack):
 trying to overwrite '/usr/bin/vba_extract.py', which is also in package python-xlsxwriter 0.9.3-1ppa1~xenial
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/python3-xlsxwriter_0.9.3-1ppa1~xenial_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
sansforensics@siftworkstation:~$ 

I don't understand enough about apt to know what the problem is. I did bang around trying to pre-delete the file it could not overwrite, but that failed spectacularly. Google did not help identify the underlying problem or a solution.  The SIFT work station is functional, but updating the underlying Ubuntu OS appears broken.
`sansforensics@siftworkstation:~$ sudo sift version
> sift-cli@1.4.0-master.129619f
> sift-version: v2017.24.1

sansforensics@siftworkstation:~$`

**Comment by VernMcC** [comment]
![image](https://user-images.githubusercontent.com/2357122/27200375-7b0fc790-51e7-11e7-9a8c-0559e5b2ab81.png)

**Comment by ekristen** [comment]
Interesting. I've run this about 1000 times on a fresh ubuntu 16.04 system. You cannot have python3 libs and python libs installed via apt unfortunately so the error is happening because of python-xlswriter already being installed and something is trying to require python3-xlswriter.

Let me try and see if I can reproduce this. I might have to mark more packages as hold to prevent getting stomped on by `apt-get upgrade`

**Comment by ekristen** [comment]
Can you provide me the output of `dpkg -l` that might help me see what is different. I just ran `apt-get upgrade` without issues, so I'm not sure what the root cause would be right now.

**Comment by VernMcC** [comment]
[dpkg.txt](https://github.com/sans-dfir/sift/files/1079017/dpkg.txt)

**Comment by VernMcC** [comment]
I am running Ubuntu desktop 16.04.2 64 bit in VMware workstation 12, with the only thing updated other than the OS is the addition of open-vm-tools-desktop. I should have time to make a video of the entire SIFT install and error and can also provide the VM if you want that too.

**Comment by ekristen** [comment]
Can you please run

```
apt-cache rdepends --installed python3-xlsxwriter
```

**Comment by VernMcC** [comment]
sansforensics@siftworkstation:~$ apt-cache rdepends --installed python3-xlsxwriter >out.txt 2>&1
sansforensics@siftworkstation:~$ cat out.txt 
python3-xlsxwriter
Reverse Depends:
  python3-plainbox
sansforensics@siftworkstation:~$ 

Also, including this image, it was the error report that pops up when I boot the VM now:
<img width="769" alt="2017-06-16 08_51_52-siftnew3 - vmware workstation" src="https://user-images.githubusercontent.com/2357122/27227633-3981ce50-5272-11e7-87ed-2d2554c0d5a1.png">

**Comment by ekristen** [comment]
Can you either continue to follow the rdepends until you get to the original or upload the VM somewhere for me to download?

**Comment by VernMcC** [comment]
Yes, compressing now, will send you the link when finished.

**Comment by Fetchered** [comment]
Having the same issue here. Brand new 16.04.2. Installed sift-cli immediately after build. Then sudo apt update -y && sudo apt upgrade -y. Exact same outputs as above (slightly different crash log though). Only difference in install is the installation of VMWare Tools vice open-vm tools.

**Comment by ekristen** [comment]
Uninstall `python3-xlsxwriter` and all will be ok. Plaso is what doesn't like python3-xlsxwriter, I'm going to see if there is a way to support it, but for now the path is manually uninstalling python3-xlsxwriter (at least for the short term)

**Comment by ekristen** [comment]
@VernMcC I'm working on fixing this. I have a build in dev right now that makes it so that plaso 1.4 can work with either python3-xlsxwriter or python-xlsxwriter. 16.04 by default requires and installed python3-xlsxwriter and it conflicts with python-xlsxwriter, so hopefully this will fix all that.

**Comment by zappeee** [comment]
@ekristen, is the fix just to install python3-xlsxwriter?
Or do I need to do anything else after?

**Comment by ekristen** [comment]
If you installed from scratch on a 16.04 install - the solution is to currently uninstall `python3-xlsxwriter`.

**Comment by cwheilig** [comment]
Installed new VM on VMware Workstation 12 Pro with ubuntu-16.04.2-desktop-amd64.iso, 
Ran apt get-update, apt get-upgrade, open-vm-tools latest. Then installed SIFT CLI instructions as per instructions (https://github.com/sans-dfir/sift-cli#instructions)

sansforensics@ubuntu:/usr/local/bin/sift$ sift --help
No command 'sift' found, did you mean:
 Command 'swift' from package 'python-swiftclient' (main)
 Command 'swift' from package 'python3-swiftclient' (universe)
 Command 'lift' from package 'lift' (universe)
 Command 'gift' from package 'gnuift' (universe)
sift: command not found

**Comment by ekristen** [comment]
@cwheilig unfortunately it seems that you didn't follow the instructions properly because your output shows you are in the directory `/usr/local/bin/sift` and it shouldn't be a directory it is a binary file. @cwheilig If you need to comment further, can you please open a new issue. This issue is for something else.

**Comment by ekristen** [comment]
@VernMcC the tests to suppose python3-xlsxwriter has failed. I do not have a solution yet. The current solution is still to remove `python3-xlsxwriter` first and then run the installation and everything will work smoothly.

**Comment by ekristen** [comment]
@VernMcC everything should be working 100% on the latest version. Let me know.

**Comment by DrVikTroll** [comment]
Hi,

I am facing the same issue, removed python3-xlsxwriter but install still fails with 15 errors on Win10, latest prod version, Ubuntu freshly installed from Win Store, updated to latest using dist-upgrade.

Tried sift install and sift install --pre-release both.

Please advise

Thanks

**Comment by ekristen** [comment]
SIFT installation has not been routinely tested on the ubuntu subsystem on Windows 10 yet. Please open a new ticket with your log files, stating you are having issues installing SIFT on ubuntu subsystem for Windows 10.
