### ISSUE TITLE
Installs are Partially Broken

### ISSUE THREAD

**Issue by ekristen** [sans-dfir/sift#641]
We are currently tracking down an issue with some python dependencies not being installable. This mostly affects python2 but does affect python3.

You'll see something like salt was installed but with some failures, around ~50 or so. Watch for this issue to be closed.

**Comment by slcamosun** [comment]
If this build is broken, which previous release should I use in its place? Thanks!

**Comment by ekristen** [comment]
None at the moment, we are working on a fix. Something changed with apt packages that are conflicting with python stuff and it's a deep nested problem that's not readily identifiable.

**Comment by ekristen** [comment]
Builds should be working again.

**Comment by randywong** [comment]
Still getting errors. After the sudo cast install, it reports 3 failed states. 

Running sift creates an erro, and says to: sudo apt install python3-guiqwt

I install that, an try sift again. This time, it asks for salt-master
I try sudo apt install salt-master, and it can't find it.
